name: plan

on:
  pull_request:
    branches:
      - '*'
jobs: 
  plan:
    name: Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
      - name: Terraform init
        run: terraform init
      - name: Run plan
        run: terraform plan
